name: Register package to GCP Artifact Registry                                    
                                                                                   
on:                                                                                
  workflow_dispatch:                                                               
  push:                                                                            
    tags:                                                                          
      - "*"                                                                        
                                                                                   
jobs:                                                                              
  register:                                                                        
    runs-on: ubuntu-latest                                                         
    steps:                                                                         
      - name: Checkout                                                             
        uses: actions/checkout@v4                                                  
                                                                                   
      - name: Setup Python                                                         
        uses: actions/setup-python@v2                                              
        with:                                                                      
          python-version: 3.11                                                     
                                                                                   
      - name: Install dependencies                                                 
        run: |                                                                     
          pip install --upgrade pip                                                
          pip install build twine keyring keyrings.google-artifactregistry-auth 
                                                                                   
      - name: Build Python package                                                 
        run: |                                                                     
          python -m build                                                          
                                                                                   
      - id: 'auth'                                                                 
        name: 'Authenticate to Google Cloud'                                       
        uses: 'google-github-actions/auth@v2'                                      
        with:                                                                      
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'                  
      - name: Upload to Artifact Registry                                          
        run: |                                                                     
          gcloud config set artifacts/repository privatepythonpackages             
          gcloud config set artifacts/location us-central1                         
          gcloud config set account github-action-pusher@my-project-1948-436821.iam.gserviceaccount.com
          gcloud auth activate-service-account github-action-pusher@my-project-1948-436821.iam.gserviceaccount.com --key-file=$GOOGLE_APPLICATION_CREDENTIALS --project=my-project-1948-436821
          gcloud artifacts print-settings python | head -n 8 > ~/.pypirc
          cat ~/.pypirc
          pip3.11 config -v list
          gcloud artifacts print-settings python | tail -n 3 > ~/pip.conf
          export PIP_CONFIG_FILE=~/pip.conf
          pip3.11 config -v list
          cat ~/pip.conf
          
      - name: Register package                                                     
        run: |                                                                     
          twine upload -r --repository-url https://us-central1-python.pkg.dev/my-project-1948-436821/privatepythonpackages/ dist/*               
